RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
EXTRAKEY_ENABLE = yes
LTO_ENABLE      = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
OLED_ENABLE = no

SRC += oneshot.c
